version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: docker/web/Dockerfile
        container_name: web
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        ports:
            - "127.0.0.1:9999:8000"
    mysql:
        container_name: mysql
        image: mysql:8
        restart: always
        # need to be changed when deploy to prod
        environment:
            MYSQL_ROOT_PASSWORD: "one-scan@1234"
            MYSQL_DATABASE: "one-scan"
            MYSQL_USER: "one-scan"
            MYSQL_PASS: "one-scan@1234"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        ports:
            - "127.0.0.1:3306:3306"

    redis:
        container_name: redis
        image: redis:latest
        restart: always
        ports:
            - "127.0.0.1:6379:6379"
